-- Immutable author-only history for every published catalogue configuration.

create table if not exists public.catalog_config_history (
  id bigint generated by default as identity primary key,
  config jsonb not null,
  saved_at timestamptz not null default now(),
  saved_by uuid,
  saved_by_email text
);

alter table public.catalog_config_history enable row level security;

revoke all on table public.catalog_config_history from anon, authenticated;
grant select on table public.catalog_config_history to authenticated;

drop policy if exists "Authors read catalogue history" on public.catalog_config_history;
create policy "Authors read catalogue history"
on public.catalog_config_history
for select
to authenticated
using ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'author');

insert into public.catalog_config_history (config, saved_at, saved_by, saved_by_email)
select config, updated_at, updated_by, null
from public.catalog_config
where id = 'main'
  and not exists (select 1 from public.catalog_config_history);

create or replace function public.record_catalog_config_history()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.catalog_config_history (config, saved_at, saved_by, saved_by_email)
  values (
    new.config,
    new.updated_at,
    new.updated_by,
    nullif((select auth.jwt() ->> 'email'), '')
  );
  return new;
end;
$$;

revoke all on function public.record_catalog_config_history() from public, anon, authenticated;

drop trigger if exists catalog_config_history_after_write on public.catalog_config;
create trigger catalog_config_history_after_write
after insert or update of config on public.catalog_config
for each row execute function public.record_catalog_config_history();

comment on table public.catalog_config_history is
  'Immutable snapshots of published catalogue configuration, readable only by authors.';
